#!/usr/bin/env bash
set -e

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [[ -n "$path" ]]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

install() {
  if [[ "$1" == "-h" ]]; then
    cat >&2 <<USAGE
Install mdub (mw).
usage: $0 <prefix>
  e.g. $0 /usr/local
USAGE
    exit 1
  fi

  local PREFIX="${1:-/usr/local}"
  local MW_ROOT="$(abs_dirname "$0")"

  mkdir -p "${PREFIX}/bin"
  cp -R "${MW_ROOT}/bin/mw" "${PREFIX}/bin"

  echo "Installed mdub (mw) to $PREFIX/bin/mw."
}

install "$@"
